<?php

//代理模式
//链接任何具有高价值或无法复制的代码。

namespace proxy;

class Record
{
    private $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function __set($name, $value)
    {
        $this->data[$name] = $value;
    }

    public function __get($name)
    {
        if (!isset($this->data[$name])) {
            echo "name is not exists";
            exit;
        }

        return $this->data[$name];
    }
}

class RecordProxy extends Record{
    private $isDirty = false;

    private $isInitalized = false;

    public function __construct($data)
    {
        parent::__construct($data);

        if(count($data) > 0){
            $this->isInitalized = true;
            $this->isDirty = true;
        }
    }

    public function __set($name, $value)
    {
        $this->isDirty = true;
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function isDirty(){
        return $this->isDirty;
    }
}